config/routes.rb
Rails.application.routes.draw do
  resources :users, only: :show do
      resources :bookings, only: :index
  end
  devise_for :user
    # controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'flats#index'
  resources :flats do
    resources :bookings, only: [:show, :new, :create]
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :amenities_flats, dependent: :destroy
  has_many :amenities, through: :amenities_flats
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :number_of_guests, presence: true
  validates :price_per_night, presence: true
  validates :address_name, presence: true
  validates :user, presence: true
  validates :city, presence: true
  validates :photos, presence: true

  geocoded_by :address_name
  after_validation :geocode, if: :will_save_change_to_address_name?

  new_flat = Flat.new
  new_flat.valid?
  new_flat.errors.messages
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @results = []
    if params[:query].present?
      sql_query = " \
        cities.name ILIKE :query \
      "
      @queried_city = params[:query]
      @result_arr = Flat.joins(:city).where(sql_query, query: "%#{params[:query]}%")
    else
      @results = Flat.joins(:city).group_by{|flat| flat.city.name}
      @host_flats = Flat.all.select {|flat| flat.user == current_user }
    end
  end


  def show
    @flats = []
    @flats << Flat.find(params[:id]) #returns flats with coordinates
    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end

    @total_reviews = @flat.reviews.length
    @review_counter = 0.0
    @flat.reviews.each do |review|
      @review_counter += review.rating
    end

    if @review_average
      @review_average = (@review_counter / @total_reviews).to_f.round(2)
    else
      @review_average = 0
      @total_reviews = 0
    end
  end

  def new
    @flat = Flat.new
    @amenities = Amenity.all
    @cities = City.all
  end

  def create
    # @city = City.find_by(params[:city_id])
    @amenities_id = params[:flat][:amenity_ids]
    @amenities_id.map! do |amenity_id|
      Amenity.find(amenity_id.to_i)
    end
    @flat = Flat.new(params_flat)
    @flat.amenities = @amenities_id
    @flat.user = current_user
    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_path(@flat), notice: "Successfully created flat"}
        format.json {}
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    @flat.update(params_flat)
    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_path(@flat), notice: "Successfully created flat"}
        format.json {}
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    redirect_to flats_path
  end

  private

  def params_flat
    params.require(:flat).permit(:name, :city_id, :description, :number_of_guests, :type_of_flat, :price_per_night, :date_check_in, :date_check_out, :address_name, :host, :city, :amenity_ids, photos: [])
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/views/flats/index.html.erb
<div class="title-welcome">
<h2>Welcome to FlatBnB</h2>
</div>


<div class="welcome-text">
  <p>" Top-rated places to stay. Explore some of the best-reviewed stays in the world."</p>
</div>



<div class="container">
  <div class="container-form">
  <%= form_tag flats_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder:  "Where do you wanna go ? "
    %>
    </div>
    <div>
      <%= submit_tag "Search", class: "btn btn-primary d-none" %>
      <% end %>
    </div>

<!-- HOST PAGE  -->

<% if !current_user.nil? && current_user.host %>
  <h3 style=" color: #666666; border-radius: 5px; font-size: 1.25rem; margin-left: 18px;">These are your flats</h3>
  <div class="card-trip">

    <% @host_flats.each do |flat| %>
        <% if flat.photos.empty? %>
          <img src="https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" />
        <% else %>
          <%= cl_image_tag flat.photos[0].key %>
        <% end %>
        <div class="card-trip-infos">
            <div>
              <h2 id="card-trip-city"><%= flat.city.name %></h2>
              <h2 id="card-trip-flat"><%= link_to flat.name.capitalize, flat_path(flat)%></h2>
            </div>
              <p class="card-trip-pricing"> <bold><%=flat.price_per_night%> $ </bold> / night </p>
          </div>
    <% end %>
  </div>
<% else %>


<!-- DEFAULT AND USER PAGE -->


  <div class="container-fluid">
      <% if @result_arr.present? %>
        <div class="city-text">
            <h5>Showing results for <%= @queried_city.capitalize %></h5>
            <p>There are <%= @result_arr.count %> available flats in <%= @queried_city.capitalize %></p>
        </div>
        <% @result_arr.each do |flat| %>
          <% if flat.photos.empty? %>
            <img src="https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" />
          <% else %>
            <%= cl_image_tag flat.photos[0].key, class: "card-img-top img-height" %>
          <% end %>
          <div class="d-flex justify-content-between card-trip-infos mb-3">
            <div class="card-body">
              <div class="city-name">
                <%= flat.city.name %>
              </div>
              <div class="card-title d-flex justify-content-between">
                <div>
                  <%= link_to flat.name.capitalize, flat_path(flat)%>
                </div>
                <div class="price_per_night">
                  <strong><%= flat.price_per_night %>$/night</strong>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>

      <% @results.each do |city_name , flats| %>
          <div class="city-text">
            <h5>Find your dream place in <%= city_name %></h5>
            <p>There are <%=flats.count%> available flats in <%= city_name %></p>
          </div>
        <div id="carousel<%= city_name %>" class="carousel slide" data-ride="carousel" data-interval="false">
          <div class="carousel-inner row w-100 mx-auto">
            <% flats.each_with_index do |flat, index| %>
              <div class="carousel-item col-md-4 <%= index == 0 ? "active" : "" %>">
                <div class="card-carousel">
                  <%= cl_image_tag flat.photos[0].key, class: "card-img-top img-height" %>
                <div class="card-body">
                  <div class="city-name">
                    <%= flat.city.name %>
                  </div>
                  <div class="card-title d-flex justify-content-between">
                    <div>
                      <%= link_to flat.name.capitalize, flat_path(flat)%>
                    </div>
                      <div class="price_per_night">
                        <strong><%= flat.price_per_night %>$/night</strong>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    <a class="carousel-control-prev" href="#carousel<%= city_name %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel<%= city_name %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

      <% end %>
      </div>
  </div>
  <% end %>



<div class="spacing"></div>

app/views/flats/new.html.erb
<div class="background mx-5">
  <div class="Header-Border text-center">
    <h1 class="Review-House-Rules"><strong>Creating Your Flat</strong></h1>
  </div>

    <div class="mb-5">
      <%= simple_form_for @flat do |f| %>
        <%= f.error_notification %>
        <%= f.input :name %>
        <%= f.input :type_of_flat %>
        <%= f.input :address_name %>
        <%= f.association :city, prompt: "Cities list" %>
        <%= f.input :description %>
        <%= f.input :price_per_night %>
        <%= f.input :number_of_guests %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <!-- got issues with the drop down selection for amenitites, cannot choose more than one amenity -->
        <%= f.association :amenities, prompt: "Amenities list", include_blank: false, include_hidden: false %>
        <%= f.button :submit, class: "btn btn-primary font-weight-bold" %>
      <% end %>
    </div>
</div>

app/views/flats/show.html.erb
<div class="header fixed-top">
  <%= link_to flats_path do %>
    <p class="back-buton"><i class="fas fa-arrow-left"></i></p>
  <% end %>
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <% (@flat.photos.length - 1).times do %>
      <% counter = 1 %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= counter %>"></li>
      <% counter += 1 %>
    <% end %>
  </ol>

  <div class="carousel-inner">
    <% @flat.photos.each_with_index do |photo, index| %>
      <% if index == 0 %>
        <div class="carousel-item active">
          <%= cl_image_tag photo.key, class: "flat-image"%>
        </div>
      <% else %>
        <div class="carousel-item">
          <%= cl_image_tag photo.key, class: "flat-image"%>
        </div>
      <% end %>
    <% end %>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  <!-- <img class="flat-image" src="https://images.unsplash.com/photo-1565330502541-4937be8552e3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80" alt=""> -->
<div class="container">

  <div class="d-flex justify-content-between">
    <div class="flat-name">
      <h1 class="flat-name-text"><%= @flat.name.capitalize %></h1>
    </div>

    <div class="flat-name d-flex">
      <i class="fas fa-star mb-0 star flat-name mt-2 mr-1"></i>
      <p class="flat-name"> <%= @review_average %> (<%= @total_reviews %>)</p> </div> </div>

  <div class="flat-name">
    <p class="flat-text">Entire House in <%= @flat.city.name %></p>
  </div>

  <div class="d-flex justify-content-start">
    <p class="flat-text-info"><%= @flat.number_of_guests %> guests</p>
    <p class="flat-text-info"><%= @flat.type_of_flat %></p>
    <p class="flat-text-info"><%= @flat.number_of_guests * 2 %> beds</p>
    <p class="flat-text-info"><%= @flat.number_of_guests %> bedroom</p>
  </div>

  <div class="description">
    <p><%= @flat.description %></p>
  </div>

  <div class="sections">
    <div class="d-flex">
      <i class="fas fa-tools amenity-logo"></i><h1 class="flat-name-text section-margin">Amenities</h1>
    </div>
    <div class="row ">
      <% @flat.amenities.each do |amenity| %>
        <div class="col-6 amenity"><%= amenity.name %> </div>
      <% end %>
    </div>
  </div>

  <div class="sections">
    <div class="d-flex">
      <i class="fas fa-map-marked-alt amenity-logo"></i><h1 class="flat-name-text section-margin">Location</h1>
    </div>
    <p class="flat-text-info"><%= @flat.address_name %></p>

      <div id="map" style="width: 100%; height: 250px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API'] %>">

      </div>



    <div>

    </div>

  </div>

   <div class="sections">
    <div class="d-flex">
      <i class="fas fa-address-card amenity-logo"></i><h1 class="flat-name-text section-margin">Your Host</h1>
    </div>
      <div class="d-flex">
                <%= cl_image_tag @flat.user.photo.key, class: "avatar-large" %>
        <p class="host-name"><%= @flat.user.first_name.capitalize %> <%= @flat.user.last_name.capitalize %></p>
      </div>
  </div>

    <div class="sections m-b-kenn">
      <div class="d-flex">
        <i class="fas fa-user-edit amenity-logo"></i><h1 class="flat-name-text section-margin">Reviews</h1>
        <% unless current_user.host %>
          <%= link_to new_flat_review_path(@flat, @review) do %>
            <p class="btn btn-primary review-buton d-none">Add Review</i></p>
          <% end %>
        <% end %>
      </div>

    <div class="d-flex flex-column mt-2 border-bottom-solid borderwidth-1 border-color-grey">
      <% @flat.reviews.each do |review| %>
        <div class="d-flex justify-content-between">
          <div class="d-flex align-items-center">
            <%= cl_image_tag review.user.photo.key, class: "avatar-large" %>
            <div class="review-bold ml-3">
            <p class="mb-0"><%= review.user.first_name %> <%= review.user.last_name %></p>
            <p class="mb-0"><%= review.created_at.strftime('%d %b %Y') %></p>
            </div>
          </div>
          <div class="stars-inline">
            <% review.rating.to_i.times do  %>
             <p><i class="fas fa-star"></i></p>
            <% end %>
            <% (5 - review.rating.to_i).times do  %>
             <p><i class="far fa-star"></i></p>
            <% end %>
          </div>
        </div>
        <p class="mt-2"><%= review.comment %></p>
      <% end %>
    </div>
    </div>

  <% unless current_user.host %>
    <div class="space-for-bar"></div>
    <div class="header d-flex justify-content-around fixed-bottom p-2">
      <div class="d-flex reserve-info">
        <p class="pernight">$<%= @flat.price_per_night %></p>
        <p class="no-left"> / night</p>
      </div>
      <%= link_to new_flat_booking_path(@flat, @booking) do %>
        <p class="btn btn-primary reserve-buton">Book now</i></p>
      <% end %>
    </div>
  <% end %>
</div>

<% @show_page = true %>