config/routes.rb
Rails.application.routes.draw do
  resources :users, only: :show do
      resources :bookings, only: :index
  end
  devise_for :user
    # controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'flats#index'
  resources :flats do
    resources :bookings, only: [:show, :new, :create]
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FlatBnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <!--    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <div class="full-view">
      <%= yield %>
    </div>
    <% unless @show_page %>
      <% if user_signed_in? %>
        <div class="footer d-flex justify-content-around fixed-bottom">
          <div class="footer-links ">
            <%= link_to user_path(current_user) do %>
            <i class="fas fa-user-circle"></i>
            <% end %>

            <%= link_to flats_path do %>
              <i class="fas fa-home"></i>
            <% end %>

            <% if current_user.host %>
              <%= link_to new_flat_path do %>
                <i class="far fa-plus-square"></i>
              <% end %>
            <% else %>
              <%= link_to user_bookings_path(current_user) do %>
                <i class="fas fa-history"></i>
              <% end %>
            <% end %>

          </div>
        </div>
      <% else %>
        <div class="footer d-flex justify-content-around fixed-bottom">
          <div class="footer-links ">
            <a href="#"><i class="fas fa-user-circle"></i></a>
            <%= link_to flats_path do %>
              <i class="fas fa-home"></i>
            <% end %>
            <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>